sudo: required
services:
  - docker

before_install:
  - docker build  -t asaforon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asaforon/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-624188022062"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
