sudo: required
services:
  - docker

before_install:
  - docker build  -t asaforon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asaforon/docker-react npm run test -- --coverage
